### ISSUE TITLE
rails g した際にエラーが発生してしまう

### ISSUE THREAD

**Issue by sasakix69** [sasakix69/You_Will_Never_Walk_Alone#6]
### 質問内容・実現したいこと

自分のポートフォリオを作っている最中での質問なのですが、`rails new`してから`rails g controller`や`rails g model`などのコマンドを入力すると以下のようなエラーが発生してしまいます。
該当部分を見ても原因が分からなかったので、考え方をご教授いただきたいです。

### 現状発生している問題・エラーメッセージ

```
sasakitenga@sasakitenganoMacBook-Air You_Will_Never_Walk_Alone % rails g controller Users index new show
/Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/railtie.rb:192:in `method_missing': undefined local variable or method `false　' for YouWillNeverWalkAlone::Application:Class (NameError)
Did you mean?  false
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/config/application.rb:29:in `block in <class:Application>'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/engine/configuration.rb:34:in `generators'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/config/application.rb:27:in `<class:Application>'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/config/application.rb:24:in `<module:YouWillNeverWalkAlone>'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/config/application.rb:22:in `<main>'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/command/actions.rb:22:in `require_application!'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/command/base.rb:69:in `perform'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/command.rb:46:in `invoke'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/commands.rb:18:in `<main>'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from bin/rails:4:in `<main>'

```

### どの処理までうまく動いているのか

`rails new`までは実行できています。

### 該当のソースコード

```
/Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/railtie.rb:192:in `method_missing': undefined local variable or method `false　' for YouWillNeverWalkAlone::Application:Class (NameError)
Did you mean?  false
```
以下、上記エラー文の該当部分です。

[![Image from Gyazo](https://i.gyazo.com/cb647f679bae94f85841806170dbe0bb.png)](https://gyazo.com/cb647f679bae94f85841806170dbe0bb)
### 試したこと

`rails db:migrate:status`や`rails s`、`rails db:create`などのコマンドを走らせても**現状発生している問題・エラーメッセージ**と同じエラー文が出ます。

### 参考にしたURL

参考になるような記事は見つかりませんでした。

**Comment by MrFuku** [comment]
@sasakix69 
`rails -v`のバージョンとGemfile.lock記載のバージョンは一致していますか？
また、railsコマンド実行時に`bundle exec`をつけるのも試してみてください。

**Comment by sasakix69** [comment]
> @sasakix69
> `rails -v`のバージョンとGemfile.lock記載のバージョンは一致していますか？

こちらはバージョン一致しております。
  
> また、railsコマンド実行時に`bundle exec`をつけるのも試してみてください。

以下、`bundle exec rails s`実行時のエラーログです。
```
sasakitenga@sasakitenganoMacBook-Air You_Will_Never_Walk_Alone % bundle exec rails s
/Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/railtie.rb:192:in `method_missing': undefined local variable or method `false　' for YouWillNeverWalkAlone::Application:Class (NameError)
Did you mean?  false
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/config/application.rb:28:in `block in <class:Application>'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/engine/configuration.rb:34:in `generators'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/config/application.rb:27:in `<class:Application>'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/config/application.rb:24:in `<module:YouWillNeverWalkAlone>'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/config/application.rb:22:in `<main>'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/activesupport-6.0.4/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/activesupport-6.0.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/activesupport-6.0.4/lib/active_support/dependencies.rb:324:in `require'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/commands/server/server_command.rb:141:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/commands/server/server_command.rb:138:in `perform'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/command/base.rb:69:in `perform'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/command.rb:46:in `invoke'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/railties-6.0.4/lib/rails/commands.rb:18:in `<main>'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/sasakitenga/workspace/runteq/portfolio/You_Will_Never_Walk_Alone/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from bin/rails:4:in `<main>'
```

以下、`rails generate`で生成しないファイルをconfig/application.rbに設定していたのですが、エラーログの`Did you mean?  false`はこのことを指しているのでしょうか？

[![Image from Gyazo](https://i.gyazo.com/56941eab3e457e330027f1de018b942c.png)](https://gyazo.com/56941eab3e457e330027f1de018b942c)

設定ファイルの書き方は書き方は合っている様に感じるのですが。

**Comment by MrFuku** [comment]
@sasakix69 
> 以下、rails generateで生成しないファイルをconfig/application.rbに設定していたのですが、エラーログのDid you mean? falseはこのことを指しているのでしょうか？

それは分かりませんが、気になるのであればその箇所を削除してrailsコマンドを試してみてください。

**Comment by MrFuku** [comment]
ちなみに`rails new`した時点では起動できていたんですか？

**Comment by sasakix69** [comment]
> ちなみに`rails new`した時点では起動できていたんですか？

`rails new`した時点では起動できていました。
```
config.generators do |g|
      g.skip_routes true
      g.assets false
      g.helper false
      g.test_framework false
end
```
上記の記述を削除してみて`rails s`したところ、サーバーが起動しmysqlがうまく起動できていないエラーが出たので、そちらを対処したところ、うまく`rails g`や`rails db:create`など始めの質問の際に動かなかったコマンドが動きました。

```
config.generators do |g|
      g.skip_routes true
      g.assets false
      g.helper false
      g.test_framework false
end
```
上記の記述をしたことでエラーが起きたのは原因不明ですが、解決致しましたのでこのまま進めて行こうと思います。
ご教授いただきありがとうございました🙇‍♂️
